<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <h1>Index</h1>
    <hr>
    <?php
        echo 'View: index.phtml';
        echo '<ul>';
        $dados = array('dado1', 'dado2', 'dado3', 'dado4'); // Definição dos dados para o exemplo
        foreach($dados as $indice => $valor): ?>
            <li><?php echo $valor; ?></li>
        <?php endforeach; ?>
    </ul>
</body>
</html>
